import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import 'bootstrap/dist/css/bootstrap.min.css';
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hurtownia Hydrauliczna",
  description: "Generated by create next app",
};

function getYear() {
  return new Date().getFullYear();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={"mb-3 text-center"}>
          <h1 className={"display-1"}>Hurtownia Hydrauliczna</h1>
        </header>
        <main>
          <nav className={"navbar navbar-expand-lg navbar-light bg-light border-bottom box-shadow m-3"}>
            <ul className={"navbar-nav m-auto"}>
              <li className={"nav-item mx-3"}><Link className={"nav-link"} href={"/"}>Strona Główna</Link></li>
              <li className={"nav-item mx-3"}><Link className={"nav-link"} href={"/shop"}>Sklep</Link></li>
              <li className={"nav-item mx-3"}><Link className={"nav-link"} href={"/partnership"}>Nasi Partnerzy</Link></li>
              <li className={"nav-item mx-3"}><Link className={"nav-link"} href={"/about"}>O Firmie</Link></li>
              <li className={"nav-item mx-3"}><Link className={"nav-link"} href={"/contact"}>Kontakt</Link></li>
            </ul>
          </nav>
          <section className={"m-3 p-3"}>
            {children}
          </section>
        </main>
        <footer className={"text-center m-3 p-3 bg-light"}>
          <p>Copyright &copy; {getYear()} Hurtownia Hydrauliczna - Mateusz Szczerek</p>
        </footer>
      </body>
    </html>
  );
}
